modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GNU LGPLv3"
issueTrackerURL = "https://github.com/MORIMORI0317/GameMenuModOption/issues"

[[mods]]
modId = "gamemenumodoption"
version = "${mod_version}"
displayName = "Game Menu Mod Option"
updateJSONURL = "https://raw.githubusercontent.com/MORIMORI0317/GameMenuModOption/master/version_check.json"
displayURL = "https://modrinth.com/mod/gamemenumodoption"
logoFile = "logo.png"
authors = "MORIMORI0317"

description = '''
A mod that adds a mod option to the game menu
The ikisugi game menu mod...
'''

[modproperties.gamemenumodoption]
catalogueImageIcon = "icon.png"

[[dependencies.gamemenumodoption]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.gamemenumodoption]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"