modLoader="javafml"
loaderVersion="[43,)"
license = "GNU LGPLv3"
issueTrackerURL = "https://github.com/MORIMORI0317/GameMenuModOption/issues"

[[mods]]
modId = "gamemenumodoption"
version = "${file.jarVersion}"
displayName = "Game Menu Mod Option"
logoFile = "logo.png"
authors = "MORIMORI0317"
description = '''
A mod that adds a mod option to the game menu
The ikisugi game menu mod...
'''

[modproperties.gamemenumodoption]
catalogueImageIcon = "logo.png"

[[dependencies.gamemenumodoption]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.gamemenumodoption]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"
