modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/MORIMORI0317/GameMenuModOption/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "gamemenumodoption"
version = "${version}"
displayName = "Game Menu Mod Option"
displayURL = "https://modrinth.com/mod/gamemenumodoption"
updateJSONURL = "https://raw.githubusercontent.com/MORIMORI0317/GameMenuModOption/master/neoforge_version_check.json"
authors = "MORIMORI0317"
description = '''
A mod that adds a mod option to the game menu
The ikisugi game menu mod...
'''
logoFile = "logo.png"
clientSideOnly=true

[modproperties.gamemenumodoption]
catalogueImageIcon = "assets/gamemenumodoption/icon.png"
catalogueBackground="assets/gamemenumodoption/background.png"
configuredBackground = "minecraft:textures/block/cobbled_deepslate.png"

[[dependencies.gamemenumodoption]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gamemenumodoption]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "gamemenumodoption-common.mixins.json"